name: ci-build

on:
  push:
    branches: 
      - '**'
    tags-ignore:
      - '**'

jobs:
  ci-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --legacy-peer-deps
    - run: npm run build --if-present
    - run: npm test
